In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../doc/fast-food.csv")

In [17]:
df.head(10)

,Company,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,McDonald’s,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5
1,McDonald’s,Cheeseburger,300.0,110.0,12.0,6.0,0.5,40.0,750.0,33.0,2.0,6.0,15.0,297.0
2,McDonald’s,Double Cheeseburger,440.0,210.0,23.0,11.0,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
3,McDonald’s,McDouble,390.0,170.0,19.0,8.0,1.0,65.0,920.0,33.0,2.0,7.0,22.0,383.0
4,McDonald’s,Quarter Pounder® with Cheese,510.0,230.0,26.0,12.0,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0
5,McDonald’s,Double Quarter Pounder® with Cheese,740.0,380.0,42.0,19.0,2.5,155.0,1380.0,40.0,3.0,9.0,48.0,720.0
6,McDonald’s,Big Mac®,540.0,260.0,29.0,10.0,1.5,75.0,1040.0,45.0,3.0,9.0,25.0,534.0
7,McDonald’s,Big N’ Tasty®,460.0,220.0,24.0,8.0,1.5,70.0,720.0,37.0,3.0,8.0,24.0,452.0
8,McDonald’s,Big N’ Tasty® with Cheese,510.0,250.0,28.0,11.0,1.5,85.0,960.0,38.0,3.0,8.0,27.0,502.0
9,McDonald’s,Angus Bacon & Cheese,790.0,350.0,39.0,17.0,2.0,145.0,2070.0,63.0,4.0,13.0,45.0,775.0

In [5]:
df.columns

Index(['Company', 'Item', 'Calories', 'Calories from\nFat', 'Total Fat\n(g)',
       'Saturated Fat\n(g)', 'Trans Fat\n(g)', 'Cholesterol\n(mg)',
       'Sodium \n(mg)', 'Carbs\n(g)', 'Fiber\n(g)', 'Sugars\n(g)',
       'Protein\n(g)', 'Weight Watchers\nPnts'],
      dtype='object')

In [9]:
df.describe()

,Company,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
count,1148,1148,1147,642,1091,1091,1091,1147,1147,1091,1091,1147,1091,887
unique,6,1072,105,64,73,35,11,65,214,131,17,122,56,524
top,McDonald’s,29 fl oz,0,0,0,0,0,0,0,0,0,0,0,0
freq,329,11,83,175,357,383,954,378,54,75,551,190,314,67

In [18]:
df.columns = [
    'Perusahaan',
    'Produk',
    'Kalori',
    'Kalori dari Lemak',
    'Total Lemak',
    'Lemak Jenuh (g)',
    'Lemak tak Jenuh (g)',
    'Kolestrol (mg)',
    'Sodium (mg)',
    'Karbohidrat (g)',
    'Serat (g)',
    'Gula (g)',
    'Protein (g)',
    'WW Poin'
]

In [19]:
df.isnull().sum()

Perusahaan             0
Produk                 0
Kalori                 0
Kalori dari Lemak      0
Total Lemak            0
Lemak Jenuh (g)        0
Lemak tak Jenuh (g)    0
Kolestrol (mg)         0
Sodium (mg)            0
Karbohidrat (g)        0
Serat (g)              0
Gula (g)               0
Protein (g)            0
WW Poin                0
dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1148 entries, 0 to 1147
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Perusahaan           1148 non-null   object
 1   Produk               1148 non-null   object
 2   Kalori               1148 non-null   float64
 3   Kalori dari Lemak    1148 non-null   float64
 4   Total Lemak          1148 non-null   float64
 5   Lemak Jenuh (g)      1148 non-null   float64
 6   Lemak tak Jenuh (g)  1148 non-null   float64
 7   Kolestrol (mg)       1148 non-null   float64
 8   Sodium (mg)          1148 non-null   float64
 9   Karbohidrat (g)      1148 non-null   float64
 10  Serat (g)            1148 non-null   float64
 11  Gula (g)             1148 non-null   float64
 12  Protein (g)          1148 non-null   float64
 13  WW Poin              1148 non-null   float64
dtypes: float64(12), object(2)
memory usage: 125.7+ KB

In [13]:
numerical_columns = [
    'Kalori', 'Kalori dari Lemak', 'Total Lemak', 'Lemak Jenuh (g)', 
    'Lemak tak Jenuh (g)', 'Kolestrol (mg)', 'Sodium (mg)', 'Karbohidrat (g)', 
    'Serat (g)', 'Gula (g)', 'Protein (g)', 'WW Poin'
]
for col in numerical_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [14]:
from sklearn.impute import SimpleImputer

numerical_imputer = SimpleImputer(strategy='mean')
df[numerical_columns] = numerical_imputer.fit_transform(df[numerical_columns])

In [16]:
df.isnull().sum()

Company                  0
Item                     0
Calories                 0
Calories from\nFat       0
Total Fat\n(g)           0
Saturated Fat\n(g)       0
Trans Fat\n(g)           0
Cholesterol\n(mg)        0
Sodium \n(mg)            0
Carbs\n(g)               0
Fiber\n(g)               0
Sugars\n(g)              0
Protein\n(g)             0
Weight Watchers\nPnts    0
dtype: int64

In [24]:
df['Perusahaan'].value_counts()

Perusahaan
McDonald’s     329
KFC            218
Burger King    190
Taco Bell      183
Wendy’s        154
Pizza Hut       74
Name: count, dtype: int64

In [25]:
company_mapping = {
    "McDonald’s": "McDollops",
    "KFC": "KrispyFiestaChicken",
    "Burger King": "Raja Burger",
    "Taco Bell": "Lonceng Teko",
    "Wendy’s": "Berangin",
    "Pizza Hut": "Pizza Topi"
}
df["Perusahaan"] = df["Perusahaan"].replace(company_mapping)

In [26]:
df.to_csv('../doc/fast-food.csv', index=False)